AWSTemplateFormatVersion: 2010-09-09
Description: A Cloudformation template to create an EC2 instance.

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0a3c3a20c09d6f377
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref SSHSecurityGroup

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
 
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyInstance
    DependsOn: MyInstance


  NewVolume:
    Type: AWS::EC2::Volume
    Properties: 
      Size: 2
      Encrypted: true
      AvailabilityZone: !GetAtt MyInstance.AvailabilityZone
      Tags:
        - Key: MyTag
          Value: TagValue
    DeletionPolicy: Delete

  MountPoint:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref MyInstance
      VolumeId: !Ref NewVolume
      Device: /dev/sdh
  
  MyUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: MyUserPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - iam:ListUsers
                  - iam:GetUser
                Resource: !GetAtt MyUser.Arn
 
  MyPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: root
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: VisualEditor0
            Effect: Allow
            Action:
              - iam:ListUsers
              - iam:GetUser
            Resource: !GetAtt MyUser.Arn
      Users:
        - !Ref MyUser