AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A starter AWS Lambda function with configurable parameters.
Parameters:
  TableName:
    Type: String
    Description: Name of the DynamoDB table.
    Default: wg-project1-users-table
  ReadCapacityUnits:
    Type: Number
    Description: Read capacity units for the DynamoDB table.
    Default: 2
    MinValue: 1
  WriteCapacityUnits:
    Type: Number
    Description: Write capacity units for the DynamoDB table.
    Default: 2
    MinValue: 1
  LambdaTimeout:
    Type: Number
    Description: Timeout in seconds for the Lambda function.
    Default: 3
    MinValue: 1
  LambdaRuntime:
    Type: String
    Description: Runtime for the Lambda function.
    Default: python3.13
    AllowedValues:
    - python3.13
  LambdaMemory:
    Type: Number
    Description: Memory Size in MB for the Lambda function.
    Default: 128
    MinValue: 128
Resources:
  MicroserviceHttpEndpoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime:
        Ref: LambdaRuntime
      CodeUri: s3://wg-bms-dev-sam-demo-v1/46514340731149faee42c288d8b3bd79
      Timeout:
        Ref: LambdaTimeout
      MemorySize:
        Ref: LambdaMemory
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TableName
          REGION_NAME:
            Ref: AWS::Region
      Events:
        HelloWorldSAMAPI:
          Type: Api
          Properties:
            Path: /hello
            Method: ANY
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TableName
  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName:
        Ref: TableName
      ProvisionedThroughput:
        ReadCapacityUnits:
          Ref: ReadCapacityUnits
        WriteCapacityUnits:
          Ref: WriteCapacityUnits
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionUri: s3://wg-bms-dev-sam-demo-v1/1ea38d3a1d96168f7c296f969240e7a3
