AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: A starter AWS lambda function
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.13
      CodeUri: s3://wg-bms-dev-sam-demo-v1/84545831987f9caa109feec34b518e4c
      Description: A started AWS lambda function
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          REGION_NAME:
            Ref: AWS::Region
      FunctionName: Lambda_Function_SAM
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic:
              Fn::ImportValue: StandardTopicArn
